name: CI
on: [push]
jobs:

  test:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-13, ubuntu-22.04, windows-2019, windows-2022]
        go: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"]

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make build

    - name: Test
      run: make test
